# Generated by Django 4.2.13 on 2024-06-22 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0002_delete_customuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_name", models.CharField(max_length=100)),
                ("profession", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="characters/images/")),
                ("pdf", models.FileField(upload_to="characters/pdfs/")),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
