# Generated by Django 4.2.13 on 2024-06-23 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterprofile",
            name="image",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="characterprofile",
            name="pdf",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="characterprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
