# Generated by Django 4.2.13 on 2024-06-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_characterprofile_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterprofile",
            name="player_name",
            field=models.CharField(default="Kuuhaku", max_length=100),
            preserve_default=False,
        ),
    ]
